version: '3'

volumes:
  mysql-data:

services:
  web-backend:
    build: ./config/backend
    container_name: web-backend
    ports:
      - 8080:80
    volumes:
      - /var/www/html:/var/www/html
      #- ./configs/backend/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /var/www/html
    environment:
      APP_ENV: local
    depends_on:
      - web-mysql
    restart: always

  web-mysql:
    container_name: web-mysql
    image: mysql:5.7.43
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: app_web1  
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  web-phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - web-mysql:mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: web-mysql
      MYSQL_ROOT_PASSWORD: ""
    depends_on:
      - web-mysql
